### PR TITLE
typos fixed

### PR DESCRIPTION
**Pull request by beumsk**

### CODE REVIEW

**Comment by beumsk** [comment]
Could you add your repo in Hacktoberfeest topic? 
Thanks!

**Review by r17x — APPROVED** [review]

**Comment by r17x** [comment]
@beumsk  thank you for fix typo

**Comment by beumsk** [comment]
It's the repository that needs Hacktoberfest not the PR. See below:
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.
Many thanks updating this :)

**Comment by faultables** [comment]
Hi @beumsk, thank you for your contribution!

Will you fix #18 too? That issue has the label hacktoberfest, so I guess it will count

**Comment by beumsk** [comment]
[This is where you should add hacktoberfest](https://github.com/evilfactorylabs/gow) 
I'll see with my time if that's possible.

**Comment by r17x** [comment]
@beumsk done for hacktoberfest topic.

Thanks

**Comment by faultables** [comment]
Hi @beumsk, any updates on this?

**Review by r17x — APPROVED** [review]

**Comment by faultables** [comment]
Your changes are applied [here](https://github.com/evilfactorylabs/gow/commit/9d0c670eca9b09d512657df226017ad6a1d6d804), thank you!

**Pull request closed without merging**
